# Generated by Django 3.2 on 2021-04-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('H', 'Hospital'), ('O', 'Oxygen'), ('P', 'Pharma')], max_length=1)),
                ('organisation_name', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoviHelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(max_length=5)),
                ('oxygen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoviHelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoviHelp.user')),
            ],
        ),
    ]
