# Generated by Django 3.2 on 2021-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviHelp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organisation_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('H', 'Hospital'), ('O', 'Oxygen'), ('P', 'Pharma'), ('B', 'Plasma Donor')], max_length=1),
        ),
    ]
