# Generated by Django 3.2 on 2021-04-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoviHelp', '0003_auto_20210425_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
    ]
