# Generated by Django 3.2 on 2021-04-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CoviHelp', '0005_auto_20210427_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='oxygen',
            old_name='oxygen_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pharma',
            old_name='pharma_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('donortype', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
