# Generated by Django 3.1.2 on 2021-04-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviHelp', '0006_auto_20210428_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oxygen',
            name='available',
        ),
        migrations.AddField(
            model_name='oxygen',
            name='city',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxygen',
            name='contact',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxygen',
            name='name',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxygen',
            name='state',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oxygen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plasma',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
